name: Redmine Git Hosting
description: A Redmine plugin which makes configuring your own Git hosting easy ;)
repository: https://github.com/jbox-web/redmine_git_hosting

github_user: jbox-web
github_repository: redmine_git_hosting

release:
  year: 2017
  version: 1.2.3
  latest_redmine_version: 3.4.2
  latest_gitolite_version: v3.6.6-6-g7c8f0ab

author:
  name: JBox Web
  url: http://www.jbox-web.com/

license:
  name: MIT
  url: http://opensource.org/licenses/MIT

# If you leave this field blank, google analytics is not run.
google_analytics: UA-36504891-3
